#  Model number on the box by the barcode is MI-B210-999W
#  This is a script for a Tuya based RGBW bulb sold by walmart under the brand Merkury.  
#  The bulb was sold for 17.88 locally.  The brightness control only effects the colors
#  A 100% brightness with 0% on all colors with white at 0% will produce a dim cool white
#  color bulb, setting a value to 100% will make the bulb that color.  This will turn the 
#  light on automatically on power on and is set by default to do so with white on 100% but 
#  can be adjusted as you see fit by changing the output settings listed between 
#  lines 28 and 32.  In this fashion the light will act similar to a normal bulb 
#  when turned on, however it will not know the difference between a turn on and a 
#  power outage so you may want to lower the brightness if used in a bedroom or use 
#  Home Assistant to turn a bulb on automatically when it connects but only outside 
#  of when you will be sleeping.
#  If you found this helpful please consider a donation through Amazon (it doesn't cost you a dime) 
#  just go here https://amzn.to/2v74aiY (Amazon affiliate link) before you make an order.

substitutions:
devicename: devicename # Edit this device name, lowercase only.

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: -10
    then:
      - light.turn_on: #turns light on white at boot.  For different color set white to 0% and color to desired level, brightness controls colors only.
          id: $devicename
          brightness: 0%
          red: 0%
          green: 0%
          blue: 0%
          white: 100%
          
wifi:
  ssid: "Your-WiFi-SSID"  # This is your desired network SSID
  password: "Your-WiFi-Password"  # This is your network password
  manual_ip:  # Set a manual IP address that will work with your network here.
    static_ip: 192.168.1.11
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename Hotspot"
    password: "Fallback-Pass"  # Edit this password.


# Enable logging to ESPHome
logger:
  # Disable logging to serial
  baud_rate: 0

# Enable Home Assistant API
api:
  
# Setup OTA password
ota:


    
output:
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO5
# Define a light entity
light:
  - platform: rgbw
    name: $devicename
    id: $devicename
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
